// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using productsncategories.Models;

namespace productsncategories.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200617230438_productsncategories2")]
    partial class productsncategories2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("productsncategories.Models.Association", b =>
                {
                    b.Property<int>("associationID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("ProductID");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("categoryID");

                    b.HasKey("associationID");

                    b.HasIndex("ProductID");

                    b.HasIndex("categoryID");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("productsncategories.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("categoryname")
                        .IsRequired();

                    b.HasKey("categoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("productsncategories.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<decimal>("price");

                    b.Property<string>("productname")
                        .IsRequired();

                    b.HasKey("productID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("productsncategories.Models.Association", b =>
                {
                    b.HasOne("productsncategories.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("productsncategories.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
